name: app

image : {pexels-alscre-3977908.webp}

type: php:8.3

runtime:
    extensions:
        - apcu
        - mbstring
        - sodium
        - iconv
        - ctype
        

  variables:
   php:
        #uncomment on PHP 7.4+
                
        opcache.preload: config/preload.php

build:
    flavor: none

disk: 2048
web:
    locations:
        "/":
            root: "web"
            passthru: "/index.php"

workers:
    messenger:
        # PHP background workers usually don't require much CPU. See
        # https://symfony.com/doc/current/cloud/cookbooks/resources_allocation.html
        # for more information
        size: XS
        resources:
            base_memory: 64 # Keep in sync with the `memory-limit` flag value
            memory_ratio: 128
        commands:
            # Don't forget to update your receiver name(s)
            start: symfony console --time-limit=3600 --memory-limit=64M messenger:consume async

mounts:
    'web/uploads': {source: local,
source_path: uploads}

hooks:
    build: |
        set -e

        curl -fs https://get.symfony.com/cloud/configurator | bash
        
        NODE_VERSION=18 symfony-build

    deploy: |
        set -e

        symfony-deploy -e